version: '3.7'

services:

  postgres:
    image: postgres
    container_name: todo_postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: todo